files:
  - source: /translations/libresvip.po
    translation: /libresvip/res/locales/%locale_with_underscore%/LC_MESSAGES/%original_file_name%
  - source: /libresvip/**/*.po
    translation: /%original_path%/locales/%locale_with_underscore%/LC_MESSAGES/%original_file_name%
