files:
  - source: /libresvip/**/*.po
    translation: /%original_path%/locales/%locale_with_underscore%/LC_MESSAGES/%original_file_name%
    ignore:
      - /%original_path%/locales/*/LC_MESSAGES/%original_file_name%
