site_name: LibreSVIP
site_author: SoulMelody
site_url: https://soulmelody.github.io/LibreSVIP/
site_description: 一个通用的歌声合成工程文件转换器
repo_name: SoulMelody/LibreSVIP
repo_url: https://github.com/SoulMelody/LibreSVIP
copyright: Copyright &copy; 2023 - 2025 SoulMelody

theme:
  name: material
  custom_dir: docs/.overrides
  features:
    - navigation.footer
    - navigation.tabs
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式
  icon:
    logo: material/file-music
    repo: material/github
  favicon: libresvip.ico
  language: zh

markdown_extensions:
  - pymdownx.snippets
  - tables

plugins:
  - marimo:
      display_code: false

nav:
  - 快速开始:
    - 简介: index.md
    - 鸣谢: credits.md
    - 开源协议: license.md
  - 开发者文档:
    - 环境搭建: setup.md
    - 贡献代码: contributing.md
    - 代码规范: coding_style.md
    - 歌声合成工程格式一览: project_formats.md
  - 常见问题: faq.md
  - 实验场: playground.md

extra:
  social:
    - icon: material/github
      link: https://github.com/SoulMelody/LibreSVIP
    - icon: material/language-python
      link: https://pypi.org/project/libresvip/
    - icon: material/translate
      link: https://zh.crowdin.com/project/libresvip
