from typing import Final

DEFAULT_CHINESE_PHONEME: Final[str] = "l a"
DEFAULT_JAPANESE_PHONEME: Final[str] = "4 a"
DEFAULT_PITCH_BEND_SENSITIVITY: Final[int] = 2
PITCH_MAX_VALUE: Final[int] = 8191
MIN_BREAK_LENGTH_BETWEEN_PITCH_SECTIONS: Final[int] = 480
BORDER_APPEND_RADIUS: Final[int] = 5
BPM_RATE: Final[float] = 100.0
