pinyin2xsampa = {
    "a": "a",
    "o": "o",
    "e": "7",
    "u": "u",
    "v": "y",
    "yu": "y",
    "yi": "i",
    "i": "i",
    "er": "@`",
    "ai": "aI",
    "ei": "ei",
    "ao": "AU",
    "ou": "@U",
    "an": "a_n",
    "en": "@_n",
    "ya": "ia",
    "ia": "ia",
    "ye": "iE_r",
    "ie": "iE_r",
    "yin": "i_n",
    "in": "i_n",
    "yong": "iUN",
    "iong": "iUN",
    "wu": "u",
    "wa": "ua",
    "ua": "ua",
    "wo": "uo",
    "uo": "uo",
    "wen": "u@_n",
    "uen": "u@_n",
    "un": "u@_n",
    "yue": "yE_r",
    "ve": "yE_r",
    "u:e": "yE_r",
    "yuan": "y{_n",
    "van": "y{_n",
    "u:an": "y{_n",
    "yun": "y_n",
    "vn": "y_n",
    "u:n": "y_n",
    "u:": "y",
    "ang": "AN",
    "yao": "iAU",
    "iao": "iAU",
    "you": "i@U",
    "iou": "i@U",
    "iu": "i@U",
    "wai": "uaI",
    "uai": "uaI",
    "wei": "uei",
    "uei": "uei",
    "ui": "uei",
    "weng": "u@N",
    "ueng": "u@N",
    "yan": "iE_n",
    "ian": "iE_n",
    "wan": "ua_n",
    "uan": "ua_n",
    "ying": "iN",
    "ing": "iN",
    "wang": "uAN",
    "uang": "uAN",
    "yang": "iAN",
    "iang": "iAN",
    "ba": "p a",
    "pa": "p_h a",
    "ma": "m a",
    "fa": "f a",
    "da": "t a",
    "ta": "t_h a",
    "na": "n a",
    "la": "l a",
    "ga": "k a",
    "ka": "k_h a",
    "ha": "x a",
    "zha": "ts` a",
    "cha": "ts`_h a",
    "sha": "s` a",
    "za": "ts a",
    "ca": "ts_h a",
    "sa": "s a",
    "bo": "p o",
    "po": "p_h o",
    "mo": "m o",
    "fo": "f o",
    "lo": "l o",
    "me": "m 7",
    "de": "t 7",
    "te": "t_h 7",
    "ne": "n 7",
    "le": "l 7",
    "ge": "k 7",
    "ke": "k_h 7",
    "he": "x 7",
    "zhe": "ts` 7",
    "che": "ts`_h 7",
    "she": "s` 7",
    "re": "z` 7",
    "ze": "ts 7",
    "ce": "ts_h 7",
    "se": "s 7",
    "zhi": "ts` i`",
    "chi": "ts`_h i`",
    "shi": "s` i`",
    "ri": "z` i`",
    "zi": "ts i\\",
    "ci": "ts_h i\\",
    "si": "s i\\",
    "bu": "p u",
    "pu": "p_h u",
    "mu": "m u",
    "fu": "f u",
    "du": "t u",
    "tu": "t_h u",
    "nu": "n u",
    "lu": "l u",
    "gu": "k u",
    "ku": "k_h u",
    "hu": "x u",
    "zhu": "ts` u",
    "chu": "ts`_h u",
    "shu": "s` u",
    "ru": "z` u",
    "zu": "ts u",
    "cu": "ts_h u",
    "su": "s u",
    "bei": "p ei",
    "pei": "p_h ei",
    "mei": "m ei",
    "fei": "f ei",
    "dei": "t ei",
    "nei": "n ei",
    "lei": "l ei",
    "gei": "k ei",
    "kei": "k_h ei",
    "hei": "x ei",
    "zhei": "ts` ei",
    "shei": "s` ei",
    "zei": "ts ei",
    "bao": "p AU",
    "pao": "p_h AU",
    "mao": "m AU",
    "dao": "t AU",
    "tao": "t_h AU",
    "nao": "n AU",
    "lao": "l AU",
    "gao": "k AU",
    "kao": "k_h AU",
    "hao": "x AU",
    "zhao": "ts` AU",
    "chao": "ts`_h AU",
    "shao": "s` AU",
    "rao": "z` AU",
    "zao": "ts AU",
    "cao": "ts_h AU",
    "sao": "s AU",
    "pou": "p_h @U",
    "mou": "m @U",
    "fou": "f @U",
    "dou": "t @U",
    "tou": "t_h @U",
    "nou": "n @U",
    "lou": "l @U",
    "gou": "k @U",
    "kou": "k_h @U",
    "hou": "x @U",
    "zhou": "ts` @U",
    "chou": "ts`_h @U",
    "shou": "s` @U",
    "rou": "z` @U",
    "zou": "ts @U",
    "cou": "ts_h @U",
    "sou": "s @U",
    "ban": "p a_n",
    "pan": "p_h a_n",
    "man": "m a_n",
    "fan": "f a_n",
    "dan": "t a_n",
    "tan": "t_h a_n",
    "nan": "n a_n",
    "lan": "l a_n",
    "gan": "k a_n",
    "kan": "k_h a_n",
    "han": "x a_n",
    "zhan": "ts` a_n",
    "chan": "ts`_h a_n",
    "shan": "s` a_n",
    "ran": "z` a_n",
    "zan": "ts a_n",
    "can": "ts_h a_n",
    "san": "s a_n",
    "ben": "p @_n",
    "pen": "p_h @_n",
    "men": "m @_n",
    "fen": "f @_n",
    "den": "t @_n",
    "nen": "n @_n",
    "gen": "k @_n",
    "ken": "k_h @_n",
    "hen": "x @_n",
    "zhen": "ts` @_n",
    "chen": "ts`_h @_n",
    "shen": "s` @_n",
    "ren": "z` @_n",
    "zen": "ts @_n",
    "cen": "ts_h @_n",
    "sen": "s @_n",
    "dong": "t UN",
    "tong": "t_h UN",
    "nong": "n UN",
    "long": "l UN",
    "gong": "k UN",
    "kong": "k_h UN",
    "hong": "x UN",
    "zhong": "ts` UN",
    "chong": "ts`_h UN",
    "rong": "z` UN",
    "zong": "ts UN",
    "cong": "ts_h UN",
    "song": "s UN",
    "bi": "p i",
    "pi": "p_h i",
    "mi": "m i",
    "di": "t i",
    "ti": "t_h i",
    "ni": "n i",
    "li": "l i",
    "ji": "ts\\ i",
    "qi": "ts\\_h i",
    "xi": "s\\ i",
    "gua": "k ua",
    "kua": "k_h ua",
    "hua": "x ua",
    "zhua": "ts` ua",
    "chua": "ts`_h ua",
    "shua": "s` ua",
    "dun": "t u@_n",
    "tun": "t_h u@_n",
    "lun": "l u@_n",
    "gun": "k u@_n",
    "kun": "k_h u@_n",
    "hun": "x u@_n",
    "zhun": "ts` u@_n",
    "chun": "ts`_h u@_n",
    "shun": "s` u@_n",
    "run": "z` u@_n",
    "zun": "ts u@_n",
    "cun": "ts_h u@_n",
    "sun": "s u@_n",
    "nu:": "n y",
    "lu:": "l y",
    "nv": "n y",
    "lv": "l y",
    "ju": "ts\\ y",
    "qu": "ts\\_h y",
    "xu": "s\\ y",
    "bai": "p aI",
    "pai": "p_h aI",
    "mai": "m aI",
    "dai": "t aI",
    "tai": "t_h aI",
    "nai": "n aI",
    "lai": "l aI",
    "gai": "k aI",
    "kai": "k_h aI",
    "hai": "x aI",
    "zhai": "ts` aI",
    "chai": "ts`_h aI",
    "shai": "s` aI",
    "zai": "ts aI",
    "cai": "ts_h aI",
    "sai": "s aI",
    "duo": "t uo",
    "tuo": "t_h uo",
    "nuo": "n uo",
    "luo": "l uo",
    "guo": "k uo",
    "kuo": "k_h uo",
    "huo": "x uo",
    "zhuo": "ts` uo",
    "chuo": "ts`_h uo",
    "shuo": "s` uo",
    "ruo": "z` uo",
    "zuo": "ts uo",
    "cuo": "ts_h uo",
    "suo": "s uo",
    "biao": "p iAU",
    "piao": "p_h iAU",
    "miao": "m iAU",
    "diao": "t iAU",
    "tiao": "t_h iAU",
    "niao": "n iAU",
    "liao": "l iAU",
    "jiao": "ts\\ iAU",
    "qiao": "ts\\_h iAU",
    "xiao": "s\\ iAU",
    "miu": "m i@U",
    "diu": "t i@U",
    "niu": "n i@U",
    "liu": "l i@U",
    "jiu": "ts\\ i@U",
    "qiu": "ts\\_h i@U",
    "xiu": "s\\ i@U",
    "guai": "k uaI",
    "kuai": "k_h uaI",
    "huai": "x uaI",
    "zhuai": "ts` uaI",
    "chuai": "ts`_h uaI",
    "shuai": "s` uaI",
    "dui": "t uei",
    "tui": "t_h uei",
    "gui": "k uei",
    "kui": "k_h uei",
    "hui": "x uei",
    "zhui": "ts` uei",
    "chui": "ts`_h uei",
    "shui": "s` uei",
    "rui": "z` uei",
    "zui": "ts uei",
    "cui": "ts_h uei",
    "sui": "s uei",
    "bang": "p AN",
    "pang": "p_h AN",
    "mang": "m AN",
    "fang": "f AN",
    "dang": "t AN",
    "tang": "t_h AN",
    "nang": "n AN",
    "lang": "l AN",
    "gang": "k AN",
    "kang": "k_h AN",
    "hang": "x AN",
    "zhang": "ts` AN",
    "chang": "ts`_h AN",
    "shang": "s` AN",
    "rang": "z` AN",
    "zang": "ts AN",
    "cang": "ts_h AN",
    "sang": "s AN",
    "beng": "p @N",
    "peng": "p_h @N",
    "meng": "m @N",
    "feng": "f @N",
    "deng": "t @N",
    "teng": "t_h @N",
    "neng": "n @N",
    "leng": "l @N",
    "geng": "k @N",
    "keng": "k_h @N",
    "heng": "x @N",
    "zheng": "ts` @N",
    "cheng": "ts`_h @N",
    "sheng": "s` @N",
    "reng": "z` @N",
    "zeng": "ts @N",
    "ceng": "ts_h @N",
    "seng": "s @N",
    "dia": "t ia",
    "lia": "l ia",
    "jia": "ts\\ ia",
    "qia": "ts\\_h ia",
    "xia": "s\\ ia",
    "bie": "p iE_r",
    "pie": "p_h iE_r",
    "mie": "m iE_r",
    "die": "t iE_r",
    "tie": "t_h iE_r",
    "nie": "n iE_r",
    "lie": "l iE_r",
    "jie": "ts\\ iE_r",
    "qie": "ts\\_h iE_r",
    "xie": "s\\ iE_r",
    "bin": "p i_n",
    "pin": "p_h i_n",
    "min": "m i_n",
    "nin": "n i_n",
    "lin": "l i_n",
    "jin": "ts\\ i_n",
    "qin": "ts\\_h i_n",
    "xin": "s\\ i_n",
    "juan": "ts\\ y{_n",
    "quan": "ts\\_h y{_n",
    "xuan": "s\\ y{_n",
    "nve": "n yE_r",
    "lve": "l yE_r",
    "jue": "ts\\ yE_r",
    "que": "ts\\_h yE_r",
    "xue": "s\\ yE_r",
    "nu:e": "n yE_r",
    "lu:e": "l yE_r",
    "duan": "t ua_n",
    "tuan": "t_h ua_n",
    "nuan": "n ua_n",
    "luan": "l ua_n",
    "guan": "k ua_n",
    "kuan": "k_h ua_n",
    "huan": "x ua_n",
    "zhuan": "ts` ua_n",
    "chuan": "ts`_h ua_n",
    "shuan": "s` ua_n",
    "ruan": "z` ua_n",
    "zuan": "ts ua_n",
    "cuan": "ts_h ua_n",
    "suan": "s ua_n",
    "jun": "ts\\ y_n",
    "qun": "ts\\_h y_n",
    "xun": "s\\ y_n",
    "bing": "p iN",
    "ping": "p_h iN",
    "ming": "m iN",
    "ding": "t iN",
    "ting": "t_h iN",
    "ning": "n iN",
    "ling": "l iN",
    "jing": "ts\\ iN",
    "qing": "ts\\_h iN",
    "xing": "s\\ iN",
    "jiong": "ts\\ iUN",
    "qiong": "ts\\_h iUN",
    "xiong": "s\\ iUN",
    "guang": "k uAN",
    "kuang": "k_h uAN",
    "huang": "x uAN",
    "zhuang": "ts` uAN",
    "chuang": "ts`_h uAN",
    "shuang": "s` uAN",
    "bian": "p iE_n",
    "pian": "p_h iE_n",
    "mian": "m iE_n",
    "dian": "t iE_n",
    "tian": "t_h iE_n",
    "nian": "n iE_n",
    "lian": "l iE_n",
    "jian": "ts\\ iE_n",
    "qian": "ts\\_h iE_n",
    "xian": "s\\ iE_n",
    "niang": "n iAN",
    "liang": "l iAN",
    "jiang": "ts\\ iAN",
    "qiang": "ts\\_h iAN",
    "xiang": "s\\ iAN",
}
