# grpclib service bindings for libresvip.proto.
#
# The message classes are generated by protoc-gen-py (see libresvip_pb.py), but
# grpclib ships no code generator for the protobuf-py runtime, so this thin
# service layer is hand-maintained. Keep it in sync with the `service Conversion`
# definition whenever the .proto changes.
from __future__ import annotations

from typing import TYPE_CHECKING

import grpclib
import grpclib.const
import grpclib.server
from grpclib.encoding.base import CodecBase

from .libresvip_pb import (
    ConversionRequest,
    ConversionResponse,
    PluginInfosRequest,
    PluginInfosResponse,
)

if TYPE_CHECKING:
    from protobuf import Message


class ProtobufPyCodec(CodecBase):
    """grpclib codec bridging protobuf-py's ``to_binary``/``from_binary`` API.

    grpclib's default ``ProtoCodec`` expects google-protobuf's
    ``SerializeToString``/``FromString``; protobuf-py exposes the equivalent
    methods under different names, so we adapt them here.
    """

    __content_subtype__ = "proto"

    def encode(self, message: Message, message_type: type[Message]) -> bytes:
        return message.to_binary()

    def decode(self, data: bytes, message_type: type[Message]) -> Message:
        return message_type.from_binary(data)


class ConversionBase:
    async def plugin_infos(self, plugin_infos_request: PluginInfosRequest) -> PluginInfosResponse:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def convert(self, conversion_request: ConversionRequest) -> ConversionResponse:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_plugin_infos(
        self, stream: grpclib.server.Stream[PluginInfosRequest, PluginInfosResponse]
    ) -> None:
        request = await stream.recv_message()
        response = await self.plugin_infos(request)
        await stream.send_message(response)

    async def __rpc_convert(
        self, stream: grpclib.server.Stream[ConversionRequest, ConversionResponse]
    ) -> None:
        request = await stream.recv_message()
        response = await self.convert(request)
        await stream.send_message(response)

    def __mapping__(self) -> dict[str, grpclib.const.Handler]:
        return {
            "/LibreSVIP.Conversion/PluginInfos": grpclib.const.Handler(
                self.__rpc_plugin_infos,
                grpclib.const.Cardinality.UNARY_UNARY,
                PluginInfosRequest,
                PluginInfosResponse,
            ),
            "/LibreSVIP.Conversion/Convert": grpclib.const.Handler(
                self.__rpc_convert,
                grpclib.const.Cardinality.UNARY_UNARY,
                ConversionRequest,
                ConversionResponse,
            ),
        }
