# Generated from libresvip/res/protos/libresvip.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.1.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Enum, Message


_PluginInfoFields: TypeAlias = Literal["identifier", "name", "version", "description", "author", "website", "json_schema", "file_format", "suffixes", "icon_base64"]

class PluginInfo(Message[_PluginInfoFields]):

    __slots__ = ("identifier", "name", "version", "description", "author", "website", "json_schema", "file_format", "suffixes", "icon_base64")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            identifier: str = "",
            name: str = "",
            version: str = "",
            description: str = "",
            author: str = "",
            website: str = "",
            json_schema: str = "",
            file_format: str = "",
            suffixes: list[str] | None = None,
            icon_base64: str = "",
        ) -> None:
            pass

        identifier: str
        name: str
        version: str
        description: str
        author: str
        website: str
        json_schema: str
        file_format: str
        suffixes: list[str]
        icon_base64: str

_PluginInfosRequestFields: TypeAlias = Literal["category", "language"]

class PluginInfosRequest(Message[_PluginInfosRequestFields]):

    __slots__ = ("category", "language")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            category: PluginCategory | None = None,
            language: str = "",
        ) -> None:
            pass

        category: PluginCategory
        language: str

_PluginInfosResponseFields: TypeAlias = Literal["values"]

class PluginInfosResponse(Message[_PluginInfosResponseFields]):

    __slots__ = ("values",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            values: list[PluginInfo] | None = None,
        ) -> None:
            pass

        values: list[PluginInfo]

_ConversionGroupFields: TypeAlias = Literal["group_id", "file_contents"]

class ConversionGroup(Message[_ConversionGroupFields]):

    __slots__ = ("group_id", "file_contents")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            group_id: str = "",
            file_contents: list[bytes] | None = None,
        ) -> None:
            pass

        group_id: str
        file_contents: list[bytes]

_ConversionRequestFields: TypeAlias = Literal["input_format", "output_format", "mode", "max_track_count", "groups", "input_options", "output_options", "middleware_options"]

class ConversionRequest(Message[_ConversionRequestFields]):

    __slots__ = ("input_format", "output_format", "mode", "max_track_count", "groups", "input_options", "output_options", "middleware_options")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            input_format: str = "",
            output_format: str = "",
            mode: ConversionMode | None = None,
            max_track_count: int = 0,
            groups: list[ConversionGroup] | None = None,
            input_options: str = "",
            output_options: str = "",
            middleware_options: dict[str, str] | None = None,
        ) -> None:
            pass

        input_format: str
        output_format: str
        mode: ConversionMode
        max_track_count: int
        groups: list[ConversionGroup]
        input_options: str
        output_options: str
        middleware_options: dict[str, str]

_SingleConversionResultFields: TypeAlias = Literal["success", "file_contents", "error_message", "warning_messages"]

class SingleConversionResult(Message[_SingleConversionResultFields]):

    __slots__ = ("success", "file_contents", "error_message", "warning_messages")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            success: bool = False,
            file_contents: list[bytes] | None = None,
            error_message: str = "",
            warning_messages: list[str] | None = None,
        ) -> None:
            pass

        success: bool
        file_contents: list[bytes]
        error_message: str
        warning_messages: list[str]

_ConversionResponseFields: TypeAlias = Literal["group_results"]

class ConversionResponse(Message[_ConversionResponseFields]):

    __slots__ = ("group_results",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            group_results: dict[str, SingleConversionResult] | None = None,
        ) -> None:
            pass

        group_results: dict[str, SingleConversionResult]

class PluginCategory(Enum):

    INPUT = 0
    OUTPUT = 1
    MIDDLEWARE = 2

class ConversionMode(Enum):

    DIRECT = 0
    SPLIT = 1
    MERGE = 2
