# Generated from libresvip.proto. DO NOT EDIT.
# Generated by protoc-gen-grpc-py v0.1.1 with parameter "io=async".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import TYPE_CHECKING

from grpc import StatusCode, method_handlers_generic_handler, unary_unary_rpc_method_handler

from .libresvip_pb import ConversionRequest, ConversionResponse, PluginInfosRequest, PluginInfosResponse

if TYPE_CHECKING:
    from grpc import aio


class ConversionServicer:
    """"""
    async def plugin_infos(self, request: PluginInfosRequest, context: aio.ServicerContext) -> PluginInfosResponse:
        """"""
        context.set_code(StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    async def convert(self, request: ConversionRequest, context: aio.ServicerContext) -> ConversionResponse:
        """"""
        context.set_code(StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def add_to_server(self, server: aio.Server) -> None:
        """Register this servicer's RPC handlers with a grpc server."""
        rpc_method_handlers = {
            "PluginInfos": unary_unary_rpc_method_handler(
                self.plugin_infos,
                request_deserializer=PluginInfosRequest.from_binary,
                response_serializer=PluginInfosResponse.to_binary,
            ),
            "Convert": unary_unary_rpc_method_handler(
                self.convert,
                request_deserializer=ConversionRequest.from_binary,
                response_serializer=ConversionResponse.to_binary,
            ),
        }
        generic_handler = method_handlers_generic_handler(
            "LibreSVIP.Conversion",
            rpc_method_handlers,
        )
        server.add_generic_rpc_handlers((generic_handler,))
