from __future__ import annotations

from enum import Enum, IntEnum
from typing import Annotated, Any, Literal

from pydantic import Field, RootModel

from libresvip.model.base import BaseModel


class BusControl(BaseModel):
    gain: float = Field(..., title="Gain")
    mute: bool = Field(..., title="Mute")
    pan: float = Field(..., title="Pan")


class ClipTime(BaseModel):
    clip_len: int = Field(
        ...,
        alias="clipLen",
        description="The clipped length relative to `clipStart`",
        title="Clipped Length (Ticks)",
    )
    clip_start: int = Field(
        ...,
        alias="clipStart",
        description="The clipped length relative to `pos`",
        title="Clipped Start (Ticks)",
    )
    length: int = Field(
        ...,
        description="The actual length of the content in the clip",
        title="Length (Ticks)",
    )
    pos: int = Field(
        ...,
        description="The position of the the clip in the timeline",
        title="Position (Ticks)",
    )


class ControlPoint(BaseModel):
    x: float = Field(..., title="X Position (Note Length Ratio)")
    y: float = Field(..., title="Y Position (Ratio)")


class ControlPoints(RootModel[list[ControlPoint]]):
    root: list[ControlPoint] = Field(..., title="Control Points")


class Label(BaseModel):
    pos: int = Field(..., title="Position (Ticks)")
    text: str = Field(..., title="Text")


class Pronunciation(BaseModel):
    edited: str = Field(..., title="Edited Pronunciation")
    original: str = Field(..., title="Original Pronunciation Generated by G2P")


class Points(BaseModel):
    amp: ControlPoints
    freq: ControlPoints


class Vibrato(BaseModel):
    amp: int = Field(..., title="Amplitude (Cent)")
    end: float = Field(..., title="End (Note Length Ratio)")
    freq: float = Field(..., title="Frequency (Hz)")
    offset: int = Field(..., title="Offset of Tune (Cent)")
    phase: float = Field(..., title="Phase")
    points: Points
    start: float = Field(..., title="Start (Note Length Ratio)")


class Interp(Enum):
    none = "none"
    linear = "linear"
    hermite = "hermite"


class Node(BaseModel):
    interp: Interp = Field(..., title="Interpolation Type")
    x: int = Field(..., title="X Position (Ticks)")
    y: int = Field(..., title="Y Position (Parameter Value)")


class ParamCurveAnchor(BaseModel):
    nodes: list[Node] = Field(..., title="Anchor Node List")
    start: int = Field(..., title="Start Position (Ticks)")
    type: Literal["anchor"] = Field(..., title="Curve Type")


class ParamCurveFree(BaseModel):
    start: int = Field(..., title="Start Position (Ticks)")
    step: Literal[5] = Field(..., title="Step (Ticks)")
    type: Literal["free"] = Field(..., title="Curve Type")
    values: list[int] = Field(..., title="Value List")


class Phoneme(BaseModel):
    language: str = Field(..., title="Language (ISO 639-3 Code)")
    onset: bool = Field(..., title="Onset Flag")
    start: int = Field(..., title="Start Position (Milliseconds from Note On)")
    token: str = Field(..., title="Phoneme Token")


class SourceMixingRatio(RootModel[list[float]]):
    root: list[float] = Field(
        ...,
        description="This array must satisfy the following conditions: 1) 0 <= each item <= 1; 2) Sum(each item) <= 1; 3) Length + 1 equals to the number of singers in the context.",
        title="Source Mixing Ratio",
    )


class Tempo(BaseModel):
    pos: int = Field(..., title="Position (Ticks)")
    value: float = Field(..., title="Tempo Value")


class Denominator(IntEnum):
    integer_1 = 1
    integer_2 = 2
    integer_4 = 4
    integer_8 = 8
    integer_16 = 16
    integer_32 = 32
    integer_64 = 64
    integer_128 = 128


class TimeSignature(BaseModel):
    denominator: Denominator = Field(..., title="Denominator")
    index: int = Field(..., title="Measure number (0-based)")
    numerator: int = Field(..., title="Numerator")


class TrackControl(BaseModel):
    gain: float = Field(..., title="Gain")
    mute: bool = Field(..., title="Mute")
    pan: float = Field(..., title="Pan")
    solo: bool = Field(..., title="Solo")


class Workspace(RootModel[dict[str, dict[str, Any]]]):
    root: dict[str, dict[str, Any]] = Field(..., title="Workspace Item")


class Global(BaseModel):
    author: str = Field(..., title="Project Author")
    cent_shift: int = Field(..., alias="centShift")
    editor_id: str = Field(..., alias="editorId", title="Editor Identifier")
    editor_name: str = Field(..., alias="editorName", title="Editor Name")
    name: str = Field(..., title="Project Name")


class Master(BaseModel):
    control: BusControl


class Timeline(BaseModel):
    labels: list[Label] = Field(..., title="Labels")
    tempos: list[Tempo] = Field(..., title="Tempos")
    time_signatures: list[TimeSignature] = Field(
        ..., alias="timeSignatures", title="Time Signatures"
    )


class AudioClip(BaseModel):
    control: BusControl
    name: str = Field(..., title="Clip Name")
    path: str = Field(..., title="Audio File Path")
    time: ClipTime
    type: Literal["audio"] = Field(..., title="Clip Type")
    workspace: Workspace


class DynamicMixingAnchor(BaseModel):
    pos: int = Field(..., title="Position (Ticks)")
    ratio: SourceMixingRatio


class Phonemes(BaseModel):
    edited: list[Phoneme] = Field(..., title="Edited Phonemes")
    original: list[Phoneme] = Field(..., title="Original Phonemes Generated from Pronunciation")


class Note(BaseModel):
    cent_shift: int = Field(..., alias="centShift")
    key_num: int = Field(..., alias="keyNum", title="MIDI Key Number")
    language: str = Field(..., title="Language (ISO 639-3 Code)")
    length: int = Field(..., title="Length (Ticks)")
    lyric: str = Field(..., title="Lyric")
    phonemes: Phonemes = Field(..., title="Phonemes")
    pos: int = Field(..., title="Position (Ticks)")
    pronunciation: Pronunciation = Field(..., title="Pronunciation")
    vibrato: Vibrato = Field(..., title="Vibrato")
    workspace: Workspace


ParamCurve = Annotated[
    ParamCurveAnchor | ParamCurveFree,
    Field(..., title="Parameter Curve", discriminator="type"),
]


class ParamCurveList(RootModel[list[ParamCurve]]):
    root: list[ParamCurve] = Field(..., title="Parameter Curve List")


class SingleSinger(BaseModel):
    extra: Any = Field(..., description="Any JSON value (implementation-specific)", title="Extra")
    id: str = Field(..., title="Singer Identifier")
    type: Literal["single"] = Field(..., title="Singer Type")
    workspace: Workspace


class Param(BaseModel):
    edited: ParamCurveList = Field(..., title="Edited Parameter Curves")
    original: ParamCurveList = Field(..., title="Original Parameter Curves")
    transform: ParamCurveList = Field(..., title="Transform Parameter Curves")


class MixedSinger(BaseModel):
    extra: Any = Field(..., description="Any JSON value (implementation-specific)", title="Extra")
    ratio: SourceMixingRatio
    singers: list[Singer] = Field(..., min_length=1, title="Singers")
    type: Literal["mixed"] = Field(..., title="Singer Type")
    workspace: Workspace


Singer = Annotated[
    SingleSinger | MixedSinger,
    Field(..., title="Singer", discriminator="type"),
]


class SingingClip(BaseModel):
    control: BusControl
    name: str = Field(..., title="Clip Name")
    notes: list[Note] = Field(..., title="Notes")
    params: dict[str, Param] = Field(..., title="Parameters")
    sources: Sources | None = Field(..., title="Sources")
    time: ClipTime
    type: Literal["singing"] = Field(..., title="Clip Type")
    workspace: Workspace


Clip = Annotated[
    AudioClip | SingingClip,
    Field(..., title="Clip", discriminator="type"),
]


class Sources(BaseModel):
    category: str = Field(..., title="Synthesis Category")
    mix: list[DynamicMixingAnchor] = Field(..., title="Dynamic Mixing Anchors")
    singers: list[Singer] = Field(..., min_length=1, title="Singers")


class Track(BaseModel):
    clips: list[Clip] = Field(..., title="Clips")
    control: TrackControl
    name: str = Field(..., title="Track Name")
    workspace: Workspace


class DspxContent(BaseModel):
    global_: Global = Field(
        ...,
        alias="global",
        description="Global metadata for the project",
        title="Global",
    )
    master: Master = Field(..., title="Master")
    timeline: Timeline = Field(..., title="Timeline")
    tracks: list[Track] = Field(..., title="Tracks")
    workspace: Workspace


class DiffscopeProjectExchangeFormat(BaseModel):
    content: DspxContent = Field(..., title="Content")
    version: Literal["1.0.0"] = Field(..., title="Version")
