from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal, TypeAlias

from pydantic import Field, ValidationInfo, field_validator

from libresvip.core.constants import DEFAULT_BPM
from libresvip.model.base import BaseModel


class BusControl(BaseModel):
    gain: float = Field(0.0, title="Gain")
    mute: bool = Field(False, title="Mute")
    pan: float = Field(0.0, title="Pan")


class ClipTime(BaseModel):
    clip_len: int = Field(
        alias="clipLen",
        description="The clipped length relative to `clipStart`",
        title="Clipped Length (Ticks)",
    )
    clip_start: int = Field(
        alias="clipStart",
        description="The clipped length relative to `start`",
        title="Clipped Start (Ticks)",
    )
    length: int = Field(
        description="The actual length of the content in the clip",
        title="Length (Ticks)",
    )
    start: int = Field(
        description="The start position of the content in the clip in the timeline",
        title="Start Position (Ticks)",
    )


class Label(BaseModel):
    pos: int = Field(0, title="Position (Ticks)")
    text: str = Field("", title="Text")


class ControlPoint(BaseModel):
    x: float = Field(title="X Position (Note Length Ratio)")
    y: float = Field(title="Y Position (Ratio)")


class DspxPronunciation(BaseModel):
    edited: str = Field("", title="Edited Pronunciation")
    original: str = Field("", title="Original Pronunciation Generated by G2P")


class VibratoPoints(BaseModel):
    amp: list[ControlPoint] = Field(default_factory=list, title="Amplitude Control Points")
    freq: list[ControlPoint] = Field(default_factory=list, title="Frequency Control Points")


class Vibrato(BaseModel):
    amp: int = Field(1, title="Amplitude (Cent)")
    end: float = Field(1.0, title="End (Note Length Ratio)")
    freq: float = Field(5.5, title="Frequency (Hz)")
    offset: int = Field(0, title="Offset of Tune (Cent)")
    phase: float = Field(0.0, title="Phase")
    points: VibratoPoints | list[ControlPoint] = Field(
        default_factory=VibratoPoints, title="Vibrato Control Points"
    )
    start: float = Field(0.0, title="Start (Note Length Ratio)")


class Interp(Enum):
    NONE = "none"
    LINEAR = "linear"
    HERMITE = "hermite"


class Node(BaseModel):
    interp: Interp = Field(Interp.NONE, title="Interpolation Type")
    x: int = Field(title="X Position (Ticks)")
    y: int = Field(title="Y Position (Parameter Value)")


class ParamCurveAnchor(BaseModel):
    nodes: list[Node] = Field(default_factory=list, title="Anchor Node List")
    start: int = Field(0, title="Start Position (Ticks)")
    type: Literal["anchor"] = Field("anchor", title="Curve Type")


class ParamCurveFree(BaseModel):
    start: int = Field(0, title="Start Position (Ticks)")
    step: Literal[5] = Field(5, title="Step (Ticks)")
    type: Literal["free"] = Field("free", title="Curve Type")
    values: list[int] = Field(default_factory=list, title="Value List")


ParamCurve = Annotated[
    ParamCurveAnchor | ParamCurveFree,
    Field(discriminator="type"),
]


class Phoneme(BaseModel):
    language: str = Field("unknown", title="Language (ISO 639-3 Code)")
    start: int = Field(0, title="Start Position (Milliseconds from Note On)")
    token: str = Field("", title="Phoneme Token")
    onset: bool = Field(False, title="Onset Flag")


class Tempo(BaseModel):
    pos: int = Field(0, title="Position (Ticks)")
    value: float = Field(DEFAULT_BPM, description="Quarter notes per minute", title="Tempo Value")


class Denominator(Enum):
    INTEGER_1 = 1
    INTEGER_2 = 2
    INTEGER_4 = 4
    INTEGER_8 = 8
    INTEGER_16 = 16
    INTEGER_32 = 32
    INTEGER_64 = 64
    INTEGER_128 = 128


class TimeSignature(BaseModel):
    denominator: Denominator = Field(Denominator.INTEGER_4, title="Denominator")
    index: int = Field(0, title="Measure number (0-based)", validate_default=True)
    numerator: int = Field(4, title="Numerator")

    @field_validator("index", mode="before")
    @classmethod
    def index_validator(cls, index: int, info: ValidationInfo) -> str:
        if info.context is not None and "start_index" in info.context:
            index = info.context["start_index"]
            info.context["start_index"] += 1
        return index


class TrackControl(BaseModel):
    gain: float = Field(0.0, title="Gain")
    mute: bool = Field(False, title="Mute")
    pan: float = Field(0.0, title="Pan")
    solo: bool = Field(False, title="Solo")


Workspace: TypeAlias = dict[str, dict[str, Any]]


class Global(BaseModel):
    author: str = Field("", title="Project Author")
    cent_shift: int = Field(0, alias="centShift")
    editor_id: str = Field("org.diffscope.diffscope", alias="editorId", title="Editor Identifier")
    editor_name: str = Field("Diffscope", alias="editorName", title="Editor Name")
    name: str = Field("", title="Project Name")


class Master(BaseModel):
    control: BusControl = Field(default_factory=BusControl, title="Master Bus Control")


class Timeline(BaseModel):
    labels: list[Label] = Field(default_factory=list, title="Labels")
    tempos: list[Tempo] = Field(default_factory=list, title="Tempos")
    time_signatures: list[TimeSignature] = Field(
        default_factory=list, alias="timeSignatures", title="Time Signatures"
    )


class BaseClip(BaseModel):
    control: BusControl = Field(default_factory=BusControl, title="Clip Control")
    name: str = Field("New Clip", title="Clip Name")
    workspace: Workspace = Field(default_factory=Workspace, title="Workspace")
    time: ClipTime


class AudioClip(BaseClip):
    path: str = Field("", title="Audio File Path")
    type: Literal["audio"] = Field("audio", title="Clip Type")


class Phonemes(BaseModel):
    edited: list[Phoneme] = Field(default_factory=list, title="Edited Phonemes")
    original: list[Phoneme] = Field(
        default_factory=list, title="Original Phonemes Generated from Pronunciation"
    )


class Note(BaseModel):
    cent_shift: int = Field(0, alias="centShift")
    key_num: int = Field(alias="keyNum", title="MIDI Key Number")
    language: str = Field("unknown", title="Language (ISO 639-3 Code)")
    length: int = Field(title="Length (Ticks)")
    lyric: str = Field(title="Lyric")
    phonemes: Phonemes = Field(default_factory=Phonemes, title="Phonemes")
    pos: int = Field(title="Position (Ticks)")
    pronunciation: DspxPronunciation = Field(
        default_factory=DspxPronunciation, title="Pronunciation"
    )
    vibrato: Vibrato = Field(default_factory=Vibrato, title="Vibrato")
    workspace: Workspace = Field(default_factory=Workspace, title="Workspace")


class Param(BaseModel):
    edited: list[ParamCurve] = Field(default_factory=list, title="Edited Parameter Curves")
    transform: list[ParamCurve] = Field(default_factory=list, title="Transform Parameter Curves")
    original: list[ParamCurve] = Field(default_factory=list, title="Original Parameter Curves")


class SingingClip(BaseClip):
    notes: list[Note] = Field(default_factory=list, title="Notes")
    params: dict[str, Param] = Field(default_factory=dict, title="Parameters")
    sources: dict[str, dict[str, Any]] = Field(default_factory=dict, title="Sources")
    type: Literal["singing"] = Field("singing", title="Clip Type")


Clip = Annotated[
    AudioClip | SingingClip,
    Field(discriminator="type"),
]


class Track(BaseModel):
    clips: list[Clip] = Field(default_factory=list, title="Clips")
    control: TrackControl = Field(default_factory=TrackControl, title="Track Control")
    name: str = Field("New Track", title="Track Name")
    workspace: Workspace


class DspxContent(BaseModel):
    global_config: Global = Field(
        default_factory=Global,
        alias="global",
        description="Global metadata for the project",
        title="Global",
    )
    master: Master = Field(default_factory=Master, title="Master")
    timeline: Timeline = Field(default_factory=Timeline, title="Timeline")
    tracks: list[Track] = Field(default_factory=list, title="Tracks")
    workspace: Workspace = Field(default_factory=Workspace, title="Workspace")


class DiffscopeProjectExchangeFormat(BaseModel):
    content: DspxContent = Field(default_factory=DspxContent, title="Content")
    version: str = Field("1.0.0", title="Version")
