version: "3"
services:
  wine_arm64:
    image: linaro/wine-arm64
    volumes:
      - ./clangarm64:/clangarm64
      - ../dist:/wheels
      - ./dist:/dist
      - ./libresvip.spec:/libresvip.spec
    command: >
      wine-arm64 cmd /c "cd / &&
      set PATH=/clangarm64/bin;%PATH% &&
      set SETUPTOOLS_USE_DISTUTILS=stdlib &&
      python -m pip install -r requirements.txt &&
      python -m pip install wheels/*.whl --no-deps &&
      pyinstaller libresvip.spec"