version: "3"
services:
  install_and_build:
    image: linaro/wine-arm64
    volumes:
      - ./python:/python
      - ../:/src
    command: >
      wine-arm64 cmd /c "cd /src/dist &&
      set PATH=/python;%PATH% &&
      python -m get-pip &&
      dir *.whl /b > requirements.txt &&
      python -m pip install -r requirements.txt --no-deps &&
      cd ../packaging &&
      python -m pip install -r requirements-web.txt --no-deps &&
      python -m PyInstaller libresvip-web.spec"