version: "3"
services:
  msys2:
    image: ghcr.io/msys2/msys2-docker-experimental
    volumes:
      - ./clangarm64:/root/.wine/drive_c/msys64/clangarm64
      - ./install_msys2_requirements.sh:/root/.wine/drive_c/install_msys2_requirements.sh:ro
    command: >
      WINEDEBUG="-all" WINEPATH="C:\\msys64\\usr\\bin" MSYSTEM="UCRT64"
      wine64 bash.exe /c/install_msys2_requirements.sh || exit 0

  wine_arm64:
    image: linaro/wine-arm64
    volumes:
      - ./clangarm64:/clangarm64
      - ../:/src
    command: >
      wine-arm64 cmd /c "cd /src/dist &&
      set PATH=/clangarm64/bin;%PATH% &&
      set SETUPTOOLS_USE_DISTUTILS=stdlib &&
      dir *.whl /b > requirements.txt &&
      python -m pip install -r requirements.txt --no-deps &&
      cd ../packaging &&
      python -m pip install -r requirements.txt &&
      python -m pip download pyinstaller==6.7.0 --platform win_arm64 --only-binary=:all: &&
      python -m wheel unpack pyinstaller-6.7.0-py3-none-win_arm64.whl" &&
      mv /src/packaging/pyinstaller-6.7.0/PyInstaller/bootloader/Windows-64bit-arm /clangarm64/lib/python3.11/site-packages/PyInstaller/bootloader &&
      ln -s /clangarm64/bin/libmediainfo-0.dll /clangarm64/lib/python3.11/site-packages/pymediainfo/ &&
      wine-arm64 cmd /c "cd /src/dist && pyinstaller libresvip.spec"
    depends_on:
      msys2:
        condition: service_completed_successfully
        restart: false