version: "3"
services:
  wine_arm64:
    image: linaro/wine-arm64
    volumes:
      - ./clangarm64:/clangarm64
      - ../:/src
    command: >
      wine-arm64 cmd /c "cd /src/dist &&
      set PATH=/clangarm64/bin;%PATH% &&
      set SETUPTOOLS_USE_DISTUTILS=stdlib &&
      dir *.whl /b > requirements.txt &&
      python -m pip install -r requirements.txt --no-deps &&
      cd ../packaging &&
      python -m pip install -r requirements.txt &&
      pyinstaller libresvip.spec"