# Generated from libresvip/res/protos/svip3.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.1.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Enum, Message

if TYPE_CHECKING:
    from protobuf.wkt import Any


_Svip3SongTempoFields: TypeAlias = Literal["pos", "tempo"]

class Svip3SongTempo(Message[_Svip3SongTempoFields]):

    __slots__ = ("pos", "tempo")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            pos: int = 0,
            tempo: int = 0,
        ) -> None:
            pass

        pos: int
        tempo: int

_Svip3SongBeatFields: TypeAlias = Literal["pos", "beat_size"]

class Svip3SongBeat(Message[_Svip3SongBeatFields]):

    __slots__ = ("pos", "beat_size")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            pos: int = 0,
            beat_size: Svip3BeatSize | None = None,
        ) -> None:
            pass

        pos: int
        beat_size: Svip3BeatSize | None

_SongToneFields: TypeAlias = Literal["pos", "tone"]

class SongTone(Message[_SongToneFields]):

    __slots__ = ("pos", "tone")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            pos: int = 0,
            tone: str = "",
        ) -> None:
            pass

        pos: int
        tone: str

_Svip3BeatSizeFields: TypeAlias = Literal["numerator", "denominator"]

class Svip3BeatSize(Message[_Svip3BeatSizeFields]):

    __slots__ = ("numerator", "denominator")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            numerator: int = 0,
            denominator: int = 0,
        ) -> None:
            pass

        numerator: int
        denominator: int

_MasterFields: TypeAlias = Literal["volume"]

class Master(Message[_MasterFields]):

    __slots__ = ("volume",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            volume: float = 0,
        ) -> None:
            pass

        volume: float

_Svip3SingingTrackFields: TypeAlias = Literal["volume", "pan", "mute", "name", "solo", "color", "type", "pattern_list", "ai_singer_id", "is_reverb_open", "reverb_type", "reverb_db", "is_rap_track"]

class Svip3SingingTrack(Message[_Svip3SingingTrackFields]):

    __slots__ = ("volume", "pan", "mute", "name", "solo", "color", "type", "pattern_list", "ai_singer_id", "is_reverb_open", "reverb_type", "reverb_db", "is_rap_track")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            volume: float = 0,
            pan: float = 0,
            mute: bool = False,
            name: str = "",
            solo: bool = False,
            color: str = "",
            type: TrackType | None = None,
            pattern_list: list[Svip3SingingPattern] | None = None,
            ai_singer_id: str = "",
            is_reverb_open: bool = False,
            reverb_type: int = 0,
            reverb_db: float = 0,
            is_rap_track: bool = False,
        ) -> None:
            pass

        volume: float
        pan: float
        mute: bool
        name: str
        solo: bool
        color: str
        type: TrackType
        pattern_list: list[Svip3SingingPattern]
        ai_singer_id: str
        is_reverb_open: bool
        reverb_type: int
        reverb_db: float
        is_rap_track: bool

_Svip3AudioTrackFields: TypeAlias = Literal["volume", "pan", "mute", "name", "solo", "color", "type", "pattern_list"]

class Svip3AudioTrack(Message[_Svip3AudioTrackFields]):

    __slots__ = ("volume", "pan", "mute", "name", "solo", "color", "type", "pattern_list")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            volume: float = 0,
            pan: float = 0,
            mute: bool = False,
            name: str = "",
            solo: bool = False,
            color: str = "",
            type: TrackType | None = None,
            pattern_list: list[Svip3AudioPattern] | None = None,
        ) -> None:
            pass

        volume: float
        pan: float
        mute: bool
        name: str
        solo: bool
        color: str
        type: TrackType
        pattern_list: list[Svip3AudioPattern]

_Svip3AudioPatternFields: TypeAlias = Literal["name", "type", "real_pos", "real_dur", "play_pos", "play_dur", "is_mute", "audio_file_path", "rising_falling_tone"]

class Svip3AudioPattern(Message[_Svip3AudioPatternFields]):

    __slots__ = ("name", "type", "real_pos", "real_dur", "play_pos", "play_dur", "is_mute", "audio_file_path", "rising_falling_tone")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            name: str = "",
            type: PatternType | None = None,
            real_pos: int = 0,
            real_dur: int = 0,
            play_pos: int = 0,
            play_dur: int = 0,
            is_mute: bool = False,
            audio_file_path: str = "",
            rising_falling_tone: float = 0,
        ) -> None:
            pass

        name: str
        type: PatternType
        real_pos: int
        real_dur: int
        play_pos: int
        play_dur: int
        is_mute: bool
        audio_file_path: str
        rising_falling_tone: float

_Svip3SingingPatternFields: TypeAlias = Literal["name", "type", "real_pos", "real_dur", "play_pos", "play_dur", "is_mute", "note_list", "edited_pitch_line", "edited_volume_line", "edited_power_line", "merge_pitch_line", "merge_power_line", "edited_spec_trans_coef_line", "edited_ap_coef_line", "edited_energy_value_line", "merge_energy_value_line", "rap_type", "singing_method_id"]

class Svip3SingingPattern(Message[_Svip3SingingPatternFields]):

    __slots__ = ("name", "type", "real_pos", "real_dur", "play_pos", "play_dur", "is_mute", "note_list", "edited_pitch_line", "edited_volume_line", "edited_power_line", "merge_pitch_line", "merge_power_line", "edited_spec_trans_coef_line", "edited_ap_coef_line", "edited_energy_value_line", "merge_energy_value_line", "rap_type", "singing_method_id")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            name: str = "",
            type: PatternType | None = None,
            real_pos: int = 0,
            real_dur: int = 0,
            play_pos: int = 0,
            play_dur: int = 0,
            is_mute: bool = False,
            note_list: list[Svip3Note] | None = None,
            edited_pitch_line: list[Svip3LineParamNode] | None = None,
            edited_volume_line: list[Svip3LineParamNode] | None = None,
            edited_power_line: list[Svip3LineParamNode] | None = None,
            merge_pitch_line: list[Svip3LineParamNode] | None = None,
            merge_power_line: list[Svip3LineParamNode] | None = None,
            edited_spec_trans_coef_line: list[Svip3LineParamNode] | None = None,
            edited_ap_coef_line: list[Svip3LineParamNode] | None = None,
            edited_energy_value_line: list[Svip3LineParamNode] | None = None,
            merge_energy_value_line: list[Svip3LineParamNode] | None = None,
            rap_type: int = 0,
            singing_method_id: str = "",
        ) -> None:
            pass

        name: str
        type: PatternType
        real_pos: int
        real_dur: int
        play_pos: int
        play_dur: int
        is_mute: bool
        note_list: list[Svip3Note]
        edited_pitch_line: list[Svip3LineParamNode]
        edited_volume_line: list[Svip3LineParamNode]
        edited_power_line: list[Svip3LineParamNode]
        merge_pitch_line: list[Svip3LineParamNode]
        merge_power_line: list[Svip3LineParamNode]
        edited_spec_trans_coef_line: list[Svip3LineParamNode]
        edited_ap_coef_line: list[Svip3LineParamNode]
        edited_energy_value_line: list[Svip3LineParamNode]
        merge_energy_value_line: list[Svip3LineParamNode]
        rap_type: int
        singing_method_id: str

_Svip3VibratoFields: TypeAlias = Literal["frequency", "amplitude", "phase", "start", "end", "attack_x", "attack_y", "release_x", "release_y"]

class Svip3Vibrato(Message[_Svip3VibratoFields]):

    __slots__ = ("frequency", "amplitude", "phase", "start", "end", "attack_x", "attack_y", "release_x", "release_y")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            frequency: float = 0,
            amplitude: float = 0,
            phase: float = 0,
            start: float = 0,
            end: float = 0,
            attack_x: float = 0,
            attack_y: float = 0,
            release_x: float = 0,
            release_y: float = 0,
        ) -> None:
            pass

        frequency: float
        amplitude: float
        phase: float
        start: float
        end: float
        attack_x: float
        attack_y: float
        release_x: float
        release_y: float

_Svip3NoteFields: TypeAlias = Literal["start_pos", "width_pos", "key_index", "lyric", "pronouncing", "consonant_len", "has_consonant", "user_consonant_len", "sp_len", "sil_len", "length_validate_tag", "vibrato", "user_sp_len", "tone", "left_pitch", "right_pitch"]

class Svip3Note(Message[_Svip3NoteFields]):

    __slots__ = ("start_pos", "width_pos", "key_index", "lyric", "pronouncing", "consonant_len", "has_consonant", "user_consonant_len", "sp_len", "sil_len", "length_validate_tag", "vibrato", "user_sp_len", "tone", "left_pitch", "right_pitch")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            start_pos: int = 0,
            width_pos: int = 0,
            key_index: int = 0,
            lyric: str = "",
            pronouncing: str = "",
            consonant_len: int = 0,
            has_consonant: bool = False,
            user_consonant_len: int = 0,
            sp_len: int = 0,
            sil_len: int = 0,
            length_validate_tag: Svip3NoteLengthValidateTag | None = None,
            vibrato: Svip3Vibrato | None = None,
            user_sp_len: int = 0,
            tone: int = 0,
            left_pitch: float = 0,
            right_pitch: float = 0,
        ) -> None:
            pass

        start_pos: int
        width_pos: int
        key_index: int
        lyric: str
        pronouncing: str
        consonant_len: int
        has_consonant: bool
        user_consonant_len: int
        sp_len: int
        sil_len: int
        length_validate_tag: Svip3NoteLengthValidateTag
        vibrato: Svip3Vibrato | None
        user_sp_len: int
        tone: int
        left_pitch: float
        right_pitch: float

_Svip3VibratoStyleFields: TypeAlias = Literal["is_anti_phase", "amp_line", "freq_line"]

class Svip3VibratoStyle(Message[_Svip3VibratoStyleFields]):

    __slots__ = ("is_anti_phase", "amp_line", "freq_line")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            is_anti_phase: bool = False,
            amp_line: list[Svip3LineParamNode] | None = None,
            freq_line: list[Svip3LineParamNode] | None = None,
        ) -> None:
            pass

        is_anti_phase: bool
        amp_line: list[Svip3LineParamNode]
        freq_line: list[Svip3LineParamNode]

_Svip3VibratoPercentInfoFields: TypeAlias = Literal["start_percent", "end_percent"]

class Svip3VibratoPercentInfo(Message[_Svip3VibratoPercentInfoFields]):

    __slots__ = ("start_percent", "end_percent")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            start_percent: float = 0,
            end_percent: float = 0,
        ) -> None:
            pass

        start_percent: float
        end_percent: float

_Svip3LineParamNodeFields: TypeAlias = Literal["pos", "value"]

class Svip3LineParamNode(Message[_Svip3LineParamNodeFields]):

    __slots__ = ("pos", "value")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            pos: int = 0,
            value: float = 0,
        ) -> None:
            pass

        pos: int
        value: float

_Svip3SongMarkFields: TypeAlias = Literal["pos", "mark"]

class Svip3SongMark(Message[_Svip3SongMarkFields]):

    __slots__ = ("pos", "mark")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            pos: int = 0,
            mark: str = "",
        ) -> None:
            pass

        pos: int
        mark: str

_Svip3ProjectFields: TypeAlias = Literal["project_file_path", "version", "duration", "tempo_list", "beat_list", "track_list", "master", "current_tone", "piano_cells", "loop_start", "loop_end", "is_open_adsorb", "params_version", "tone_list", "is_triplets", "is_loop", "is_last_play", "mark_list"]

class Svip3Project(Message[_Svip3ProjectFields]):

    __slots__ = ("project_file_path", "version", "duration", "tempo_list", "beat_list", "track_list", "master", "current_tone", "piano_cells", "loop_start", "loop_end", "is_open_adsorb", "params_version", "tone_list", "is_triplets", "is_loop", "is_last_play", "mark_list")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            project_file_path: str = "",
            version: str = "",
            duration: int = 0,
            tempo_list: list[Svip3SongTempo] | None = None,
            beat_list: list[Svip3SongBeat] | None = None,
            track_list: list[Any] | None = None,
            master: Master | None = None,
            current_tone: str = "",
            piano_cells: int = 0,
            loop_start: int = 0,
            loop_end: int = 0,
            is_open_adsorb: bool = False,
            params_version: int = 0,
            tone_list: list[SongTone] | None = None,
            is_triplets: bool = False,
            is_loop: bool = False,
            is_last_play: bool = False,
            mark_list: list[Svip3SongMark] | None = None,
        ) -> None:
            pass

        project_file_path: str
        version: str
        duration: int
        tempo_list: list[Svip3SongTempo]
        beat_list: list[Svip3SongBeat]
        track_list: list[Any]
        master: Master | None
        current_tone: str
        piano_cells: int
        loop_start: int
        loop_end: int
        is_open_adsorb: bool
        params_version: int
        tone_list: list[SongTone]
        is_triplets: bool
        is_loop: bool
        is_last_play: bool
        mark_list: list[Svip3SongMark]

class TrackType(Enum):

    Track_None = 0
    Audio_Track = 1
    Singing_Track = 2

class PatternType(Enum):

    Pattern_None = 0
    Audio_Pattern = 1
    Singing_Pattern = 2

class Svip3NoteLengthValidateTag(Enum):

    NONE = 0
    TOO_LONG = 1
    TOO_SHORT = 2
