name: pre-commit
on:
  pull_request:
  push:
    branches: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "latest"
      - name: Install linting dependencies
        run: |
          uv sync --all-extras --group linting
      - uses: j178/prek-action@v2
